#!/bin/bash
set -e

cd $(dirname $0)

echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
apt-get update
apt-get install -y --no-install-recommends openjdk-7-jdk maven python-pip 

DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install -y mysql-server postgresql-9.4

pip install --upgrade pip==6.0.3 tox==1.8.1 virtualenv==12.0.4

install_build_tools()
{
	BUILD_TOOLS_VERSION="0.1.0"
	tmpdir=$(mktemp -d)
	pushd $tmpdir
	curl -sSL -o build-tools.tar.gz https://github.com/rancherio/build-tools/archive/v${BUILD_TOOLS_VERSION}.tar.gz
	tar -xzvf build-tools.tar.gz && cp ./build-tools-${BUILD_TOOLS_VERSION}/bin/* /usr/bin
	popd
	rm -rf ${tmpdir}
}
install_build_tools

if [ "${CATTLE_DB_CATTLE_DATABASE}" == "mysql" ]; then
    ./bootstrap-mysql
fi

if [ -x /usr/bin/cattle-binary-pull ] && [ -f ../resources/content/cattle-global.properties ]; then
    /usr/bin/cattle-binary-pull ../resources/content/cattle-global.properties /usr/bin
fi
